import {
  createRouter,
  createWebHashHistory,
  type RouteRecordRaw
} from "vue-router"

export const Layout = () => import('@/layouts/index.vue')
export const routes: RouteRecordRaw[] = [
  {
    path: "",
    name: "首页",
    component: Layout,
    redirect: "dashboard",
    meta: {
      title: "首页",
      icon: "system",
      hidden: false,
      alwaysShow: false,
      params: null,
    },
    children: [
      {
        path: "dashboard",
        component: () => import("@/views/dashboard/index.vue"),
        name: "面板",
        meta: {
          title: "面板",
          icon: "homepage",
          affix: true,
          keepAlive: true,
        },
      },

    ]
  },
  {
    path: "/system",
    component: Layout,
    redirect: "/system/user",
    name: "/system",
    meta: {
      title: "系统管理",
      icon: "system",
      hidden: false,
      alwaysShow: false,
      params: null,
    },
    children: [
      {
        path: "user",
        component: () => import('@/views/UserView/index.vue'),
        name: "User",
        meta: {
          title: "用户管理",
          icon: "el-icon-User",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "role",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Role",
        meta: {
          title: "角色管理",
          icon: "role",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "menu",
        component: () => import('@/views/AboutView/index.vue'),
        name: "SysMenu",
        meta: {
          title: "菜单管理",
          icon: "menu",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "dept",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Dept",
        meta: {
          title: "部门管理",
          icon: "tree",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "dict",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Dict",
        meta: {
          title: "字典管理",
          icon: "dict",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "log",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Log",
        meta: {
          title: "系统日志",
          icon: "document",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "dict-item",
        component: () => import('@/views/AboutView/index.vue'),
        name: "DictItem",
        meta: {
          title: "字典项",
          icon: "",
          hidden: true,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "config",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Config",
        meta: {
          title: "系统配置",
          icon: "setting",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "notice",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Notice",
        meta: {
          title: "通知公告",
          icon: "",
          hidden: false,
          alwaysShow: false,
          params: null,
        },
      },
    ],
  },
  {
    path: "/codegen",
    component: Layout,
    name: "/codegen",
    meta: {
      title: "系统工具",
      icon: "menu",
      hidden: false,
      alwaysShow: false,
      params: null,
    },
    children: [
      {
        path: "codegen",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Codegen",
        meta: {
          title: "代码生成",
          icon: "code",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
    ],
  },
  {
    path: "/api",
    component: Layout,
    name: "/api",
    meta: {
      title: "接口文档",
      icon: "api",
      hidden: false,
      alwaysShow: true,
      params: null,
    },
    children: [
      {
        path: "apifox",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Apifox",
        meta: {
          title: "Apifox",
          icon: "api",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
    ],
  },
  {
    path: "/doc",
    component: Layout,
    redirect: "https://juejin.cn/post/7228990409909108793",
    name: "/doc",
    meta: {
      title: "平台文档",
      icon: "document",
      hidden: false,
      alwaysShow: false,
      params: null,
    },
    children: [
      {
        path: "internal-doc",
        component: () => import('@/views/AboutView/index.vue'),
        name: "InternalDoc",
        meta: {
          title: "document",
          icon: "document",
          hidden: false,
          alwaysShow: false,
          params: null,
        },
      },
    ],
  },
  {
    path: "/multi-level",
    component: Layout,
    name: "/multiLevel",
    meta: {
      title: "多级菜单",
      icon: "cascader",
      hidden: false,
      alwaysShow: true,
      params: null,
    },
    children: [
      {
        path: "multi-level1",
        component: Layout,
        name: "MultiLevel1",
        meta: {
          title: "菜单一级",
          icon: "",
          hidden: false,
          alwaysShow: true,
          params: null,
        },
        children: [
          {
            path: "multi-level2",
            component: Layout,
            name: "MultiLevel2",
            meta: {
              title: "菜单二级",
              icon: "",
              hidden: false,
              alwaysShow: false,
              params: null,
            },
            children: [
              {
                path: "multi-level3-1",
                component: () => import('@/views/AboutView/index.vue'),
                name: "MultiLevel31",
                meta: {
                  title: "菜单三级-1",
                  icon: "",
                  hidden: false,
                  keepAlive: true,
                  alwaysShow: false,
                  params: null,
                },
              },
              {
                path: "multi-level3-2",
                component: () => import('@/views/AboutView/index.vue'),
                name: "MultiLevel32",
                meta: {
                  title: "菜单三级-2",
                  icon: "",
                  hidden: false,
                  keepAlive: true,
                  alwaysShow: false,
                  params: null,
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    path: "/component",
    component: Layout,
    name: "/component",
    meta: {
      title: "组件封装",
      icon: "menu",
      hidden: false,
      alwaysShow: false,
      params: null,
    },
    children: [
      {
        path: "curd",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Curd",
        meta: {
          title: "增删改查",
          icon: "",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "table-select",
        component: () => import('@/views/AboutView/index.vue'),
        name: "TableSelect",
        meta: {
          title: "列表选择器",
          icon: "",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "wang-editor",
        component: () => import('@/views/AboutView/index.vue'),
        name: "WangEditor",
        meta: {
          title: "富文本编辑器",
          icon: "",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "upload",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Upload",
        meta: {
          title: "图片上传",
          icon: "",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "dict-demo",
        component: () => import('@/views/AboutView/index.vue'),
        name: "DictDemo",
        meta: {
          title: "字典组件",
          icon: "",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "icon-selector",
        component: () => import('@/views/AboutView/index.vue'),
        name: "IconSelector",
        meta: {
          title: "图标选择器",
          icon: "",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "drag",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Drag",
        meta: {
          title: "拖拽组件",
          icon: "",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "text-scroll",
        component: () => import('@/views/AboutView/index.vue'),
        name: "TextScroll",
        meta: {
          title: "滚动文本",
          icon: "",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
    ],
  },
  {
    path: "/route-param",
    component: Layout,
    name: "/routeParam",
    meta: {
      title: "路由参数",
      icon: "el-icon-ElementPlus",
      hidden: false,
      alwaysShow: true,
      params: null,
    },
    children: [
      {
        path: "route-param-type1",
        component: () => import('@/views/AboutView/index.vue'),
        name: "RouteParamType1",
        meta: {
          title: "参数(type=1)",
          icon: "el-icon-Star",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: {
            type: "1",
          },
        },
      },
      {
        path: "route-param-type2",
        component: () => import('@/views/AboutView/index.vue'),
        name: "RouteParamType2",
        meta: {
          title: "参数(type=2)",
          icon: "el-icon-StarFilled",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: {
            type: "2",
          },
        },
      },
    ],
  },
  {
    path: "/function",
    component: Layout,
    name: "/function",
    meta: {
      title: "功能演示",
      icon: "menu",
      hidden: false,
      alwaysShow: false,
      params: null,
    },
    children: [
      {
        path: "vxe-table",
        component: () => import('@/views/AboutView/index.vue'),
        name: "VxeTable",
        meta: {
          title: "VxeTable",
          icon: "el-icon-MagicStick",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "icon-demo",
        component: () => import('@/views/AboutView/index.vue'),
        name: "IconDemo",
        meta: {
          title: "Icons",
          icon: "el-icon-Notification",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "/function/websocket",
        component: () => import('@/views/AboutView/index.vue'),
        name: "/function/websocket",
        meta: {
          title: "Websocket",
          icon: "",
          hidden: false,
          keepAlive: true,
          alwaysShow: false,
          params: null,
        },
      },
      {
        path: "other/:id",
        component: () => import('@/views/AboutView/index.vue'),
        name: "Other/:id",
        meta: {
          title: "敬请期待...",
          icon: "",
          hidden: false,
          alwaysShow: false,
          params: null,
        },
      },
    ],
  },
]

const router = createRouter({
  history: createWebHashHistory(),
  routes: routes,
})

export default router
